#!/usr/bin/env -S perl -pi
s/^(elseif\(APPLE\))/$1\n  set_target_properties(nlua0 PROPERTIES OSX_ARCHITECTURES "\${CMAKE_SYSTEM_PROCESSOR}")/;
s/^(if\(APPLE\))/$1\n  list(APPEND DEPS_CMAKE_ARGS "-DCMAKE_OSX_ARCHITECTURES=\${CMAKE_OSX_ARCHITECTURES}")/;
s/(  CMAKE_ARGS \${DEPS_CMAKE_ARGS})/$1 "-DCMAKE_OSX_ARCHITECTURES=\${CMAKE_SYSTEM_PROCESSOR}"/;
